# Site
repository: umairadeeb/umairadeeb.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Umair Adeeb Shahid
title: Sr. DevOps/Platform Engineer
email: Umairr@gmail.com
website: umairadeeb.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: umairadeeb
github_username:  umairadeeb
# stackoverflow_username: "2234859"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: umairadeeb
linkedin_username: umairadeeb
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/umairadeeb.jpg
about_content: | # this will include new lines to allow paragraphs
  A results-driven DevOps/Platform engineer with extensive experience in designing and managing scalable solutions for diverse IT environments. Proficient in a wide range of technical skills, I am committed to optimizing system performance and reliability.
  My expertise spans across various areas including Kubernetes, CI/CD tools, Cloud platforms, Virtualization, IaC, and on-call rotations for incident response teams.

  Technical skills/tools:
  <mark>Linux system administration</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>Infrastructure as Code (IaC Terraform)</mark>, <mark>GitHub Actions</mark>, <mark>GitLab CI</mark>, <mark>Jenkins</mark>, <mark>ArgoCD</mark>, <mark>argo-rollouts</mark>, <mark>Spinnaker</mark>, <mark>kOps</mark>, <mark>GKE</mark>, <mark>EKS</mark>, <mark>ECS</mark>, <mark>Puppet</mark>, <mark>Ansible</mark>, <mark>Bash</mark>, <mark>Python</mark>, <mark>Jfrog Artifactory</mark>, <mark>DataDog</mark>, <mark>Prometheus</mark>, <mark>Grafana stack</mark>, <mark>OpsGenie</mark>, <mark>PagerDuty</mark>, <mark>Keeper Secrets Manager</mark>, <mark>AWS Secrets Manager</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

#########################
#  E X P E R I E N C E  #
#########################

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PPRO Holding GmbH
        link: https://www.ppro.com/
        # link_text: boringcompany.com
        sub_title: Senior DevOps Engineer
        caption: August 2020 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Led the VCS Migration Project to GitHub:
                - Spearheaded the successful migration of VCS from GitLab to GitHub.
                - Moved source code, MR history, comments, & pipelines seamlessly

            - Developed Self-Service Repository Provisioning Tool with Terraform/Terragrunt:
                - Automated the application of security best practices, ensuring adherence to standards

            - Implemented Repository Configuration Validation Workflow:
                - Created a crucial workflow to validate configs for security compliance that prevents unauthorized changes by blocking PRs & pipelines

            - Established Self-Service ECS-Based GitHub Runners:
                - Enabled ephemeral provisioning of runners as ECS tasks to reduce cost of running self-hosted runners while allowing access to private VPCs

            - Deployed Google Kubernetes Engine Based GitHub Runners:
                - Supported resource-intensive builds, enhancing performance

            - Designed Secrets Management System with Keeper Security:
                - Ensured standardized secret storage for CI/CD and cloud deployments

            - Managed Multi-Environment Kubernetes Clusters with kOps:
                - Ensured high availability and scalability of the Kubernetes infrastructure

            - Administered Kubernetes Tooling and Continuous Deployment:
                - Sealed-secrets, Kube2iam, Cert-manager, External-DNS, Ingress Controllers, & a Prometheus monitoring stack
                - Continuous Deployment (CD) using ArgoCD & Argo-Rollouts, supporting multiple deployment strategies

            - Implemented DataDog-Based App and Service Monitoring:
                - Designed and maintained comprehensive monitoring solutions with integrations, monitors, and dashboards

            - Established GitLab Shared Pipeline Library:
                - Set up a GitLab shared pipeline library, similar to Jenkins, to streamline the development process

            - Managed Terraform-Based Infrastructure as Code (IaC) Repositories:
                - For AWS, GCP, GitHub, Keeper Secrets Manager, and partially for Okta

            - Provided On-Call Support and Incident Remediation

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wirecard Acceptance Technologies
        link: https://www.wirecard.com/
        sub_title: DevOps Engineer
        caption: March 2020 - July 2020
        description: | # this will include new lines to allow paragraphs
            - Deployment automation using Rundeck and puppet.
            - Implementation of GitOps practices using GitLab CI.
            - Create metrics to help with implementation of SLI and SLOs.
            - Immutable deployments on virtual machines using puppet and terraform.
            - Write Puppet modules to automate execution of deployments.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nisum Technologies
        link: https://www.nisum.com/
        sub_title: Lead DevOps Engineer
        caption: November 2017 - February 2020
        description: | # this will include new lines to allow paragraphs
            - Create CI/CI pipelines using modular Jenkins Shared Library.
            - Deployment and Container orchestration using Kubernetes, and Cloud Foundry.
            - Automate build and deployment of e-commerce applications using Jenkins, Chef/Ansible, ISTIO, and Spinnaker.
            - Design automated deployments using Docker compose, Helm charts. 
            - Rewrite node initialization and setup of prerequisites from bash to Chef in local mode.
            - Setup and automate deployments on Microsoft Azure and Google Cloud.
            - Automate completion of deployment prerequisites on servers using Ansible.
            - Develop complete CI/CD pipelines using Jenkins, Gitlab/Github, Kubernetes, ISTIO, and Spinnaker
            - Prepare best practices based on POC on Deployment Strategies (blue/green, rolling updates, canary, blue/green with canary)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Primatics Financial
        link: https://www.ssctech.com/products/evolv
        sub_title: Senior Systems Administrator
        caption: March 2013 - October 2017
        description: | # this will include new lines to allow paragraphs
            - Management and administration of RHEL 6/7, CENTOS 6/7, Oracle Enterprise Linux 6 servers.
            - Management of Amazon EC2 based linux servers.
            - Management and administration of RightScale (UI and API) to automate operations of Amazon EC2
            - Management of Amazon's S3 storage, and OpsWorks
            - Administration and pipelines of CI tools like TeamCity and Travis
            - Deployment of MS Windows components using TeamCity builds
            - Complete management and administration of Puppet + MCollective along with its integration with GitLab VCS.
            - Logs management and analysis using Splunk, Logstash, and Graylog2
            - Management and administration of NMS tools like Zabbix, PagerDuty, and PRTG.
            - Management and administration of Virtualization and Storage technologies which includes VMWare, EMC VMAX, and XtremIO.
            - Complete implementation of Docker in existing infrastructure and product stack including storage and networking.
            - Development and administration of Docker Containers and automation using Dockerfile.
            - Management and Administration of Alfresco Server.
            - Management, Administration and Deployment of JBOSS Server.
            - Bash scripting to automate different technological pieces.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left  
        title: GFK Etilize
        link: https://www.etilize.com/
        sub_title: System Administrator
        caption: January 2011 - March 2013
        description: | # this will include new lines to allow paragraphs
            - Monitoring, Management, and Administration of linux (Redhat, Fedora, CentOS) based local, and remote (EC2, Rackspace) Servers.
            - Administration, Management, Deployment, and Configuration of JAVA based TOMCAT web applications on local and remote servers.
            - Monitoring, Management and Administration of MySQL based database servers.
            - Write bash / php / python scripts to automate processes and tasks.
            - Developed PHP & MySQL based application for accounts administration of Open LDAP based directory server.
            - Developed PHP & MySQL based application for centralized logging of linux services (/var/log/messages, apache log, proftpd log etc).
            - Feasibility, testing, and migration of around 150 users from Windows XP to Ubuntu 12.04.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left  
        title: Sybrid
        link: https://www.sybrid.com/
        sub_title: System Support Engineer
        caption: July 2010 - December 2010
        description: | # this will include new lines to allow paragraphs
            - Completed a project of migration of the existing systems and desktop users to Free and Open Source alternatives to provide cost effective solutions. The scope of the project was:
            - Migration of end-users to Ubuntu operating system from Microsoft Windows XP, Windows Vista or Windows 7.
            - Migration of Email Services from Google hosted email server to Zimbra Collaboration Suite (Community Edition).
            - Migration from ISA Proxy Server to Linux based proxy / Mikrotik Router OS
            - Migration from Microsoft’s active directory to Linux’s Open LDAP / Samba services

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: System Support Engineer
        link: https://ptcl.com.pk/
        sub_title: System Support Engineer
        caption: March 2008 - July 2010
        description: | # this will include new lines to allow paragraphs
            - Development and Maintenance of Online Web Portal.
            - Management & administration of Zimbra Collaboration Suite Email Server.
            - Management & administration of linux based servers.
            - User Administration (ZTE Agent Management Application / Portal)


#######################
#  E D U C A T I O N  #
#######################

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mohammad Ali Jinnah University, Pakistan
        caption: 2010 - 2014
        sub_title: MBA - Information Systems
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
#          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Karachi, Pakistan
        caption: 2008 - 2010
        sub_title: Bachelor of Commerce

#################################
#  C E R T I F I C A T I O N S  #
#################################

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Site Reliability Engineering - Measuring and Managing Reliability
        caption: March 2020
        sub_title: Google

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Google Certified Associate Cloud Engineer
        caption: 2019 - 2021
        sub_title: Google Cloud

#########################################
#    I N T E R E S T S / H O B B I E S  #
#########################################

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cloud, devops, and automation, some of my other interests and hobbies are:
      - Hiking
      - [Photography](https://500px.com/p/umairadeeb)
      - Gaming


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
