# Site
repository: umairadeeb/umairadeeb.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Umair Adeeb Shahid
title: Sr. DevOps/Platform Engineer
email: Umairr@gmail.com
website: umairadeeb.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: umairadeeb
github_username:  umairadeeb
# stackoverflow_username: "2234859"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: umairadeeb
linkedin_username: umairadeeb
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/umairadeeb.jpg
about_content: | # this will include new lines to allow paragraphs
  A results-driven DevOps/Platform engineer with extensive experience in designing and managing scalable solutions for diverse IT environments. Proficient in a wide range of technical skills, I am committed to optimizing system performance and reliability.
  My expertise spans across various areas including Kubernetes, CI/CD tools, Cloud platforms, Virtualization, IaC, and on-call rotations for incident response teams.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

  Technical skills/tools:
  <mark>Linux system administration</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>Infrastructure as Code (IaC Terraform)</mark>, <mark>GitHub Actions</mark>, <mark>GitLab CI</mark>, <mark>Jenkins</mark>, <mark>ArgoCD</mark>, <mark>argo-rollouts</mark>, <mark>Spinnaker</mark>, <mark>kOps</mark>, <mark>GKE</mark>, <mark>EKS</mark>, <mark>ECS</mark>, <mark>Puppet</mark>, <mark>Ansible</mark>, <mark>Bash</mark>, <mark>Python</mark>, <mark>Jfrog Artifactory</mark>, <mark>DataDog</mark>, <mark>Prometheus</mark>, <mark>Grafana stack</mark>, <mark>OpsGenie</mark>, <mark>PagerDuty</mark>, <mark>Keeper Secrets Manager</mark>, <mark>AWS Secrets Manager</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PPRO Holding GmbH
        link: https://www.ppro.com/
        # link_text: boringcompany.com
        sub_title: Senior DevOps Engineer
        caption: August 2020 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Led the VCS Migration Project to GitHub:
              Spearheaded the successful migration of VCS from GitLab to GitHub.
              Moved source code, MR history, comments, & pipelines seamlessly

            - Developed Self-Service Repository Provisioning Tool with Terraform/Terragrunt:
              Automated the application of security best practices, ensuring adherence to standards

            - Implemented Repository Configuration Validation Workflow:
              Created a crucial workflow to validate configs for security compliance that prevents unauthorized changes by blocking PRs & pipelines

            - Established Self-Service ECS-Based GitHub Runners:
              Enabled ephemeral provisioning of runners as ECS tasks to reduce cost of running self-hosted runners while allowing access to private VPCs

            - Deployed Google Kubernetes Engine Based GitHub Runners:
              Supported resource-intensive builds, enhancing performance

            - Designed Secrets Management System with Keeper Security:
              Ensured standardized secret storage for CI/CD and cloud deployments

            - Managed Multi-Environment Kubernetes Clusters with kOps:
              Ensured high availability and scalability of the Kubernetes infrastructure

            - Administered Kubernetes Tooling and Continuous Deployment:
              Sealed-secrets, Kube2iam, Cert-manager, External-DNS, Ingress Controllers, & a Prometheus monitoring stack
              Continuous Deployment (CD) using ArgoCD & Argo-Rollouts, supporting multiple deployment strategies

            - Implemented DataDog-Based App and Service Monitoring:
              Designed and maintained comprehensive monitoring solutions with integrations, monitors, and dashboards

            - Established GitLab Shared Pipeline Library:
              Set up a GitLab shared pipeline library, similar to Jenkins, to streamline the development process

            - Managed Terraform-Based Infrastructure as Code (IaC) Repositories:
              For AWS, GCP, GitHub, Keeper Secrets Manager, and partially for Okta

            - Provided On-Call Support and Incident Remediation


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
